---
# tasks file for roles/database
- name: Run database
  docker_container:
    name: database
    image: dorianmat/database
    state: started
    networks: 
     - name: ntwdo
    env: 
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      